import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins instead of Inter
import "./globals.css";

// Specify the font weights and styles you need
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Example: Regular, Medium, Bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
